allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true

overrides:
  "@codemirror/state": "^6.5.2"
  "@codemirror/view": "^6.38.2"
  "@codemirror/language": "^6.11.3"
  "@codemirror/commands": "^6.8.1"
  "codemirror": "^6.0.2"
