crowdin:
  project_id: "modpackstore"
  api_token: ""
  base_path: "."
  base_url: "https://api.crowdin.com"

  files:
    - source: "/application/src-tauri/resources/i18n/en.yml"
      translation: "/application/src-tauri/resources/i18n/%locale%.yml"
      languages_mapping:
        locale:
          es-419: "es-419"
          pt-BR: "pt-BR"
          fr: "fr"
          de: "de"
          it: "it"
          ru: "ru"
          zh-CN: "zh-CN"
          ja: "ja"
          ko: "ko"