name: Publish Canary

on:
  push:
    branches: [main]
    paths:
      - 'application/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  publish-canary-linux:
    name: Build & Publish for Linux (Ubuntu 20.04)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ This step is now corrected
      - name: Install Linux build dependencies
        run: |
          sudo apt-get install -y libwebkit2gtk-4.1-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf


      - name: Setup Environment & Build
        uses: ./.github/actions/setup-and-build
        with:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}


  publish-canary-windows:
    name: Build & Publish for Windows
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Environment & Build
        uses: ./.github/actions/setup-and-build
        with:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}