# .github/workflows/publish-canary.yml (versión final)

name: Publish Canary

on:
  push:
    branches: [main]
    paths: ['application/**', '.github/workflows/**']

jobs:
  publish-canary-linux:
    name: Build & Publish for Linux
    runs-on: ubuntu-latest
    permissions: { contents: write }
    container: { image: ubuntu:20.04 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # ✅ Usas tu acción compuesta para todos los pasos comunes
      - name: Setup Environment & Build
        uses: ./.github/actions/setup-and-build # <-- ¡Toda la lógica repetida está aquí!
        with:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
      # Paso específico de Linux
      - name: Install Linux build dependencies
        run: |
          apt-get update && apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

  publish-canary-windows:
    name: Build & Publish for Windows
    runs-on: windows-latest
    permissions: { contents: write }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # ✅ Reutilizas la misma acción aquí
      - name: Setup Environment & Build
        uses: ./.github/actions/setup-and-build
        with:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}