name: Publish Canary

on:
  push:
    branches:
      - main
    paths:
      - 'application/**'
      - '.github/workflows/**'

jobs:
  publish-canary:
    name: Build & Publish for ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Combina la instalación de pnpm y la configuración de su caché de la forma más simple
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # O 'latest'

      - name: Set up Node.js with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install frontend dependencies
        working-directory: ./application/
        run: pnpm install --frozen-lockfile

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      # ✅ Integra tus opciones avanzadas para el caché de Rust
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './application' # Ruta simplificada
          cache-on-failure: true
          cache-all-crates: true
          # Condición inteligente: Solo se actualiza el caché en la rama 'main'
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install Linux build dependencies
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Build & Publish Canary Release
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          GITHUB_REPOSITORY: ModpackStore/ModpackStore-Releases
        with:
          projectPath: ./application
          tagName: canary
          releaseName: Canary Build canary
          releaseBody: Automated canary build for testing
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
          owner: ModpackStore
          repo: ModpackStore-Releases